default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  host: mysql-container
  username: user
  password: pass
  database: database

development:
  main:
    <<: *default
  sub:
    <<: *default

test:
  main:
    <<: *default
  sub:
    <<: *default

production:
  main:
    <<: *default
    host: main-host
    password: main-pass
  sub:
    <<: *default
    host: sub-host
    password: sub-pass
    replica: true
